### ISSUE TITLE
How to write an implementation of a factory?

### ISSUE THREAD

**Issue by tariano** [nicolascotton/nject#55]
The [`Inject providers for post-creation value injection`](https://docs.rs/nject/latest/nject/index.html#inject-providers-for-post-creation-value-injection) section shows how to write factories, but I'm failing to understand how to create a factory with my own custom implementation.

For instance, what if the value of the `Dep` struct in that example would have to be fetched asynchronously from a DB via my own custom function:
```rust
impl DepFactory {
	async fn get_johnny(&self, my_db:Db) -> Dep {
		await my_db.get_johnny()
	}
}
```

Thanks in advance!

**Comment by nicolascotton** [comment]
Hi @tariano,

I'm not sure I understand correctly. Are you asking how to provide an async value?
If that's the case, here's what you can do:
```rust
use nject::{injectable, provider};
use std::{future::Future, pin::Pin};

#[derive(Debug)]
struct Dep(i32);

#[injectable]
struct Db;

impl Db {
    fn fetch_dep(&self) -> impl Future<Output = Dep> {
        async { Dep(123) }
    }
}

// We cannot use impl Future in traits, so we have to pin box. Maybe it will be supported in the future.
type FutureDep = Pin<Box<dyn Future<Output = Dep>>>;

#[provider]
// You can provide any factory for a provided type.
// NOTE: I would not recommend injecting non-deterministic values.
#[provide(FutureDep, |db: Db| Box::pin(db.fetch_dep()))]
struct Provider;

#[tokio::main]
async fn main() {
    let dep = Provider.provide::<FutureDep>().await;
    println!("{dep:?}");
}
```
Let me know if this helped.
